"""Regression check for the v1.4 scenarios refactor.

Asserts that adding scenarios doesn't make any *currently-visible* listing
disappear. Specifically:

  1. Every finn_id in the previous production output (data/scored_latest.json)
     must still appear in the new pipeline output — in the "main" lane,
     or in an alt-scenario lane (an alt-scenario placement is a softer
     signal change but still preserves the listing).
  2. The new pipeline must keep at least as many listings as production did.
     Alt scenarios should ADD listings, never subtract.
  3. The scenario distribution should be non-empty for "main" and at
     least one alt should fire (otherwise the feature isn't doing anything
     against the real data).

Run:
    python -m tests.test_scenarios_regression
or:
    python tests/test_scenarios_regression.py

Exit code: 0 = pass, 1 = regression detected.

This is a scrape-data-driven check, not a unit test — it depends on
data/listings_latest.json and data/scored_latest.json being present
(committed or generated by a recent local run). Treat it as a "before
merging the scenarios branch" gate, not a CI gate.
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path


def _finn_ids(scored_dicts) -> set[str]:
    out = set()
    for r in scored_dicts:
        l = r.get("listing") or {}
        fid = l.get("finn_id")
        if fid is not None:
            out.add(str(fid))
    return out


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    sys.path.insert(0, str(repo_root))

    import yaml
    from src.filters import apply_hard_filters
    from src.scorer import score_listings

    cfg = yaml.safe_load((repo_root / "config" / "scoring_config.yaml").read_text())

    listings_path = repo_root / "data" / "listings_latest.json"
    scored_path = repo_root / "data" / "scored_latest.json"
    if not listings_path.exists():
        print(f"FAIL: missing {listings_path}", file=sys.stderr)
        return 1
    if not scored_path.exists():
        print(f"FAIL: missing {scored_path} — need a production baseline", file=sys.stderr)
        return 1

    listings = json.loads(listings_path.read_text())
    prod = json.loads(scored_path.read_text())
    prod_ids = _finn_ids(prod)

    kept, _dropped = apply_hard_filters(listings, cfg)
    kept_dicts = [
        {
            "listing": r.listing,
            "passed": True,
            "failed": r.failed,
            "unverified": r.unverified,
            "scenario": r.scenario,
            "main_scenario_fails": r.main_scenario_fails,
        }
        for r in kept
    ]
    scored = score_listings(kept_dicts, cfg, baseline_listings=listings)
    scored_dicts = [s.to_dict() for s in scored]

    # Distribution
    dist = Counter(s.get("scenario") or "main" for s in scored_dicts)
    print(f"Production baseline: {len(prod_ids)} listings")
    print(f"New pipeline:        {len(scored_dicts)} listings")
    print(f"  main:        {dist.get('main', 0)}")
    print(f"  scenario_1:  {dist.get('scenario_1', 0)}")
    print(f"  scenario_2:  {dist.get('scenario_2', 0)}")
    print()

    failures = []

    # Check 1: every prod listing still appears somewhere
    new_all_ids = _finn_ids(scored_dicts)
    missing = prod_ids - new_all_ids
    if missing:
        # Note: filter pass 1 (this script) doesn't include detail-page
        # filtering (floor, sold, dealbreaker), so missing ⊆ prod_ids would
        # be unusual — production sees fewer detail-stage drops than this
        # bare-filter regression run. Surface anyway for inspection.
        failures.append(
            f"REGRESSION: {len(missing)} listing(s) in production no longer "
            f"appear in any lane: {sorted(missing)[:10]}"
        )

    # Check 2: total kept ≥ production baseline
    if len(scored_dicts) < len(prod_ids):
        failures.append(
            f"REGRESSION: new pipeline kept {len(scored_dicts)} listings, "
            f"production had {len(prod_ids)} — alt scenarios should ADD, "
            f"not subtract"
        )

    # Check 3: at least one scenario non-empty
    if dist.get("main", 0) == 0:
        failures.append(
            "WARN: main lane is empty — either the cached scrape is stale "
            "or the location_caps moved"
        )
    if dist.get("scenario_1", 0) == 0 and dist.get("scenario_2", 0) == 0:
        failures.append(
            "WARN: both alt scenarios are empty — either the scrape data "
            "doesn't trigger them or the thresholds aren't tuned right"
        )

    if failures:
        print("=" * 60)
        for f in failures:
            print(f)
        print("=" * 60)
        # WARNs don't fail the script; only REGRESSIONs do.
        regressions = [f for f in failures if f.startswith("REGRESSION")]
        if regressions:
            print(f"\nFAIL: {len(regressions)} regression(s)")
            return 1
        else:
            print(f"\nPASS (with {len(failures)} warning(s))")
            return 0

    print("PASS — all production listings preserved, distribution healthy")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
